######################################################################
# Automatically generated by qmake (2.01a) dim. 7. févr. 01:40:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += release

DESTDIR = ./

# Input
HEADERS += Corewar.h Program.h Field.h
SOURCES += Corewar.cpp Program.cpp Field.cpp

TRANSLATIONS = corewar2_fr.ts
CODECFORTR = ISO-8859-1
