######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 7 01:40:24 2010
######################################################################

TEMPLATE = app
TARGET = corewar2
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

CONFIG += release

DESTDIR = ./

# Input
HEADERS += Corewar.h Program.h Field.h
SOURCES += Corewar.cpp Program.cpp Field.cpp

TRANSLATIONS = corewar2_fr.ts
CODECFORTR = UTF-8
